import { createClient } from '@/utils/supabase/server';
import { FileText, Image as ImageIcon } from 'lucide-react';
import LogoUploader from './components/LogoUploader';
import TemplateList from './components/TemplateList';

export const dynamic = 'force-dynamic';

export default async function AdminTemplatesPage() {
    const supabase = await createClient();

    // Get organization ID
    const { data: orgs } = await supabase.from('organizations').select('id').limit(1).single();
    const orgId = orgs?.id;

    if (!orgId) {
        return <div className="p-8 text-center text-slate-500">Organization not found.</div>;
    }

    // Get logo setting
    const { data: logoSetting } = await supabase
        .from('settings')
        .select('setting_value')
        .eq('org_id', orgId)
        .eq('setting_key', 'company_logo')
        .single();

    const logoUrl = (logoSetting?.setting_value as { url?: string })?.url || '';

    // Get existing templates
    const { data: templates } = await supabase
        .from('document_templates')
        .select('id, name, slug, type, updated_at')
        .eq('org_id', orgId);

    return (
        <div className="space-y-10 max-w-5xl mx-auto pb-12">
            <div>
                <h1 className="text-2xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
                    <FileText className="h-6 w-6 text-indigo-600" />
                    System Templates
                </h1>
                <p className="text-sm text-slate-500 mt-1">Configure company branding and document templates used throughout the TMS.</p>
            </div>

            <section className="space-y-4">
                <div className="flex items-center gap-2 border-b border-slate-100 pb-2">
                    <ImageIcon className="h-5 w-5 text-indigo-600" />
                    <h2 className="text-lg font-semibold text-slate-800">Branding</h2>
                </div>
                <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm">
                    <LogoUploader initialLogoUrl={logoUrl} orgId={orgId} />
                </div>
            </section>

            <section className="space-y-4">
                <div className="flex items-center gap-2 border-b border-slate-100 pb-2">
                    <FileText className="h-5 w-5 text-indigo-600" />
                    <h2 className="text-lg font-semibold text-slate-800">Document Forms</h2>
                </div>
                <div className="space-y-2 mb-4">
                    <p className="text-sm text-slate-500">
                        Customize the HTML/CSS for various documents generated by the system. If no custom template is provided, the system defaults will be used.
                    </p>
                </div>
                <TemplateList templates={templates || []} />
            </section>
        </div>
    );
}
