import { createClient } from '@/utils/supabase/server';
import TemplateEditor from '../components/TemplateEditor';
import { notFound } from 'next/navigation';

export const dynamic = 'force-dynamic';

const DEFAULT_TEMPLATES: Record<string, { name: string, type: string, content: string }> = {
    'bol': {
        name: 'BOL Template',
        type: 'BOL',
        content: `
<style>
    body { font-family: sans-serif; padding: 20px; color: #1e293b; }
    .header { display: flex; justify-content: space-between; border-bottom: 2px solid #334155; padding-bottom: 10px; margin-bottom: 20px; }
    .title { font-size: 24px; font-weight: bold; color: #0f172a; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
    .section-title { font-size: 10px; font-weight: bold; text-transform: uppercase; color: #64748b; margin-bottom: 5px; }
    .section-content { font-size: 14px; line-height: 1.4; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { text-align: left; background: #f8fafc; border-bottom: 1px solid #e2e8f0; padding: 10px; font-size: 12px; }
    td { padding: 10px; border-bottom: 1px solid #f1f5f9; font-size: 13px; }
    .footer { margin-top: 50px; border-top: 1px solid #e2e8f0; pt: 20px; font-size: 10px; color: #94a3b8; text-align: center; }
</style>

<div class="header">
    <div>
        <div class="title">BILL OF LADING</div>
        <div style="font-size: 12px; margin-top: 5px;">LOAD #: {{load_number}}</div>
    </div>
    <div style="text-align: right;">
        <div style="font-weight: bold;">{{company_name}}</div>
        <div style="font-size: 12px;">Date: {{pickup_date}}</div>
    </div>
</div>

<div class="grid">
    <div>
        <div class="section-title">Shipper</div>
        <div class="section-content">
            <strong>{{shipper_name}}</strong><br>
            {{shipper_address}}
        </div>
    </div>
    <div>
        <div class="section-title">Consignee</div>
        <div class="section-content">
            <strong>{{consignee_name}}</strong><br>
            {{consignee_address}}
        </div>
    </div>
</div>

<div style="margin: 20px 0; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;">
    <div class="section-title">Special Instructions</div>
    <div style="font-size: 13px;">Please call 24 hours prior to delivery. All freight must be counted and signed for by consignee.</div>
</div>

<table>
    <thead>
        <tr>
            <th>DESCRIPTION</th>
            <th>PIECES</th>
            <th>WEIGHT</th>
            <th>CLASS</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>General Freight</td>
            <td>{{total_pallets}} PLT</td>
            <td>{{total_weight}} LBS</td>
            <td>70</td>
        </tr>
    </tbody>
</table>

<div class="footer">
    Generated by {{company_name}} TMS. Reference PRO: {{pro_number}} | BOL: {{bol_number}}
</div>
`
    },
    'customer-invoice': {
        name: 'Customer Invoice',
        type: 'Invoice',
        content: `
<style>
    body { font-family: Inter, sans-serif; padding: 40px; color: #334155; }
    .inv-header { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .inv-title { font-size: 32px; font-weight: 800; color: #1e293b; }
    .bill-to { margin-bottom: 40px; }
    .bill-label { font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; margin-bottom: 8px; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 40px; }
    th { text-align: left; padding: 12px 15px; border-bottom: 2px solid #e2e8f0; font-size: 12px; text-transform: uppercase; color: #64748b; }
    td { padding: 15px; border-bottom: 1px solid #f1f5f9; font-size: 14px; }
    .total-box { margin-left: auto; width: 250px; background: #f8fafc; padding: 20px; border-radius: 12px; }
    .total-row { display: flex; justify-content: space-between; margin-bottom: 10px; }
    .total-grand { border-top: 1px solid #e2e8f0; padding-top: 10px; font-weight: 800; color: #0f172a; font-size: 18px; }
</style>

<div class="inv-header">
    <div>
        <div class="inv-title">INVOICE</div>
        <div style="margin-top: 10px; font-weight: 600;"># INV-{{load_number}}</div>
    </div>
    <div style="text-align: right;">
        <div style="font-weight: 800; font-size: 18px;">{{company_name}}</div>
        <div style="font-size: 12px; margin-top: 4px;">123 Logistics Way, Suite 100</div>
        <div style="font-size: 12px;">Support: (555) 123-4567</div>
    </div>
</div>

<div class="bill-to">
    <div class="bill-label">Bill To</div>
    <div style="font-size: 16px; font-weight: 600;">{{customer_name}}</div>
</div>

<table>
    <thead>
        <tr>
            <th>Service Description</th>
            <th>Reference</th>
            <th style="text-align: right;">Amount</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><strong>Freight Transportation Services</strong><br><span style="font-size: 11px; color: #64748b;">{{shipper_name}} to {{consignee_name}}</span></td>
            <td>{{load_number}}</td>
            <td style="text-align: right; font-weight: 600;">{{customer_rate}}</td>
        </tr>
    </tbody>
</table>

<div class="total-box">
    <div class="total-row">
        <span style="font-size: 12px; color: #64748b;">Subtotal</span>
        <span style="font-weight: 600;">{{customer_rate}}</span>
    </div>
    <div class="total-row">
        <span style="font-size: 12px; color: #64748b;">Tax (0%)</span>
        <span style="font-weight: 600;">$0.00</span>
    </div>
    <div class="total-row total-grand">
        <span>Total Due</span>
        <span>{{customer_rate}}</span>
    </div>
</div>

<div style="margin-top: 60px; font-size: 12px; color: #64748b; line-height: 1.6;">
    <strong>Payment Terms:</strong> Net 30. Please make checks payable to {{company_name}}. Reference Invoice # INV-{{load_number}} on all payments.
</div>
`
    },
    'customer-rate-quote-ltl': {
        name: 'LTL Rate Quote',
        type: 'Quote',
        content: `
<style>
    body { font-family: Inter, sans-serif; padding: 40px; color: #334155; }
    .quote-box { border: 1px solid #e2e8f0; border-radius: 16px; padding: 32px; background: white; }
    .tag { display: inline-block; background: #e0e7ff; color: #4338ca; font-size: 10px; font-weight: 800; padding: 4px 10px; border-radius: 99px; text-transform: uppercase; margin-bottom: 12px; }
    .quote-title { font-size: 28px; font-weight: 800; color: #1e293b; margin-bottom: 32px; }
    .route { display: flex; align-items: center; gap: 24px; margin-bottom: 40px; border-bottom: 1px solid #f1f5f9; padding-bottom: 24px; }
    .location { flex: 1; }
    .loc-label { font-size: 11px; font-weight: bold; color: #94a3b8; text-transform: uppercase; margin-bottom: 4px; }
    .loc-val { font-size: 16px; font-weight: 700; color: #1e293b; }
    .rate-display { background: #f8fafc; border-radius: 12px; padding: 24px; display: flex; justify-content: space-between; align-items: center; }
</style>

<div class="quote-box">
    <div class="tag">Standard LTL Quote</div>
    <div class="quote-title">Rate Quotation #{{load_number}}</div>

    <div class="route">
        <div class="location">
            <div class="loc-label">Origin</div>
            <div class="loc-val">{{shipper_name}}</div>
            <div style="font-size: 13px; color: #64748b; margin-top: 4px;">{{shipper_address}}</div>
        </div>
        <div style="font-size: 24px; color: #cbd5e1;">&rarr;</div>
        <div class="location">
            <div class="loc-label">Destination</div>
            <div class="loc-val">{{consignee_name}}</div>
            <div style="font-size: 13px; color: #64748b; margin-top: 4px;">{{consignee_address}}</div>
        </div>
    </div>

    <div style="margin-bottom: 32px;">
        <div class="loc-label">Shipment Details</div>
        <div style="font-size: 14px;"><strong>Weight:</strong> {{total_weight}} LBS | <strong>Dimensions:</strong> Standard Pallets ({{total_pallets}})</div>
    </div>

    <div class="rate-display">
        <div>
            <div style="font-size: 13px; font-weight: 600; color: #64748b;">All-In Estimated Rate</div>
            <div style="font-size: 12px; color: #94a3b8; margin-top: 2px;">Subject to re-weigh and re-class</div>
        </div>
        <div style="font-size: 36px; font-weight: 800; color: #4338ca;">{{customer_rate}}</div>
    </div>

    <div style="margin-top: 32px; font-size: 11px; color: #94a3b8; line-height: 1.5;">
        Quote provided by {{company_name}}. Rates are valid for 7 days. Standard transit times apply.
    </div>
</div>
`
    },
    'customer-spot-rate-quote': {
        name: 'Spot Rate Quote',
        type: 'Quote',
        content: `
<style>
    body { font-family: sans-serif; padding: 40px; color: #1e293b; background: #f1f5f9; }
    .card { background: white; border-radius: 12px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); padding: 40px; max-width: 800px; margin: 0 auto; border-top: 6px solid #6366f1; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 30px; }
    .quote-id { font-size: 12px; font-weight: 800; color: #6366f1; background: #e0e7ff; padding: 4px 12px; border-radius: 99px; }
    .title { font-size: 28px; font-weight: 800; margin: 15px 0; }
    .details { display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }
    .label { font-size: 11px; font-weight: bold; text-transform: uppercase; color: #94a3b8; margin-bottom: 5px; }
    .val { font-size: 15px; font-weight: 600; }
    .items-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin-top: 30px; padding: 20px; background: #f8fafc; border-radius: 8px; }
    .rate-section { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: right; }
    .price { font-size: 48px; font-weight: 900; color: #1e293b; }
</style>

<div class="card">
    <div class="header">
        <div>
            <span class="quote-id">SPOT QUOTE #{{load_number}}</span>
            <h1 class="title">Rate Proposal</h1>
        </div>
        <div style="text-align: right;">
            <div style="font-weight: bold;">{{company_name}}</div>
            <div style="font-size: 13px; color: #64748b;">Date: {{quote_date}}</div>
            <div style="font-size: 13px; color: #64748b;">Valid until: 24 Hours from now</div>
        </div>
    </div>

    <div class="details">
        <div>
            <div class="label">Origin</div>
            <div class="val">{{shipper_name}}</div>
            <div style="font-size: 13px; color: #64748b;">{{shipper_address}}</div>
        </div>
        <div>
            <div class="label">Destination</div>
            <div class="val">{{consignee_name}}</div>
            <div style="font-size: 13px; color: #64748b;">{{consignee_address}}</div>
        </div>
    <div style="margin-top: 30px;">
        <div class="label">Carrier</div>
        <div class="val">{{carrier_name}}</div>
    </div>

    <div class="items-grid">
        <div>
            <div class="label">Pieces / Type</div>
            <div class="val">{{pcs}} {{type}}</div>
        </div>
        <div>
            <div class="label">Weight</div>
            <div class="val">{{weight}} lbs</div>
        </div>
        <div>
            <div class="label">Cubic Ft</div>
            <div class="val">{{cubic_ft}} cu ft</div>
        </div>
    </div>

    <div style="margin-top: 30px;">
        <div class="label">Products</div>
        <div class="val">
            <table style="width: 100%; border-collapse: collapse; margin-top: 5px; background: white;">
                <thead>
                    <tr style="font-size: 10px; color: #94a3b8; border-bottom: 1px solid #e2e8f0;">
                        <th style="padding: 5px; text-align: left;">QTY</th>
                        <th style="padding: 5px; text-align: left;">TYPE</th>
                        <th style="padding: 5px; text-align: left;">DESC</th>
                        <th style="padding: 5px; text-align: right;">WT</th>
                    </tr>
                </thead>
                <tbody>
                    {{#each products}}
                    <tr style="font-size: 12px; border-bottom: 1px solid #f1f5f9;">
                        <td style="padding: 5px;">{{pcs}}</td>
                        <td style="padding: 5px;">{{type}}</td>
                        <td style="padding: 5px;">{{description}}</td>
                        <td style="padding: 5px; text-align: right;">{{weight}} lbs</td>
                    </tr>
                    {{/each}}
                </tbody>
            </table>
        </div>
    </div>

    <div style="margin-top: 20px;">
        <div class="label">Accessorials</div>
        <div class="val">
            {{#each accessorials_names}}
            <span style="display: inline-block; background: #f1f5f9; padding: 2px 8px; border-radius: 4px; margin-right: 5px; margin-bottom: 5px; font-size: 12px;">{{this}}</span>
            {{/each}}
        </div>
    </div>

    <div style="margin-top: 20px;">
        <div class="label">Additional Instructions</div>
        <div class="val" style="font-weight: normal; font-style: italic;">{{additional_instructions}}</div>
    </div>

    <div class="rate-section">
        <div class="label">All-In Spot Rate</div>
        <div class="price">{{customer_rate}}</div>
    </div>
</div>
`
    },
    'customer-load-confirmation': {
        name: 'Customer Load Confirmation',
        type: 'Confirmation',
        content: `
<style>
    body { font-family: 'Helvetica', sans-serif; padding: 30px; }
    .conf-header { text-align: center; border-bottom: 3px solid #1e293b; padding-bottom: 20px; margin-bottom: 30px; }
    .conf-title { font-size: 26px; font-weight: bold; letter-spacing: 2px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0px; border: 1px solid #000; }
    .info-cell { padding: 10px; border: 0.5px solid #000; }
    .label { font-size: 10px; font-weight: bold; text-transform: uppercase; margin-bottom: 3px; }
    .value { font-size: 13px; font-weight: bold; }
</style>

<div class="conf-header">
    <div class="conf-title">CUSTOMER LOAD CONFIRMATION</div>
    <div style="font-size: 14px; margin-top: 5px;">Reference Number: {{load_number}}</div>
</div>

<div class="info-grid">
    <div class="info-cell">
        <div class="label">Shipper</div>
        <div class="value">{{shipper_name}}</div>
        <div class="value">{{shipper_address}}</div>
    </div>
    <div class="info-cell">
        <div class="label">Consignee</div>
        <div class="value">{{consignee_name}}</div>
        <div class="value">{{consignee_address}}</div>
    </div>
    <div class="info-cell">
        <div class="label">Pickup Date</div>
        <div class="value">{{pickup_date}}</div>
    </div>
    <div class="info-cell">
        <div class="label">Delivery Date</div>
        <div class="value">{{delivery_date}}</div>
    </div>
</div>

<div style="margin-top: 20px; border: 1px solid #000; padding: 15px;">
    <div class="label">Load Description</div>
    <div style="font-size: 13px;">{{total_pallets}} Pallets, {{total_weight}} LBS of General Freight.</div>
</div>

<div style="margin-top: 20px; text-align: right;">
    <div style="font-size: 16px;"><strong>Agreed Rate: {{customer_rate}}</strong></div>
</div>

<div style="margin-top: 40px; font-size: 11px;">
    <p>By accepting this load, the customer agrees to the terms and conditions set forth by {{company_name}}.</p>
</div>
`
    },
    'carrier-load-confirmation': {
        name: 'Carrier Load Confirmation',
        type: 'Confirmation',
        content: `
<style>
    body { font-family: sans-serif; padding: 30px; }
    .header { display: flex; justify-content: space-between; border-bottom: 2px solid #000; padding-bottom: 10px; }
    .main-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px; }
    .stop { border: 1px solid #e2e8f0; padding: 15px; border-radius: 4px; }
    .stop-header { background: #f8fafc; margin: -15px -15px 15px -15px; padding: 10px 15px; border-bottom: 1px solid #e2e8f0; font-weight: bold; }
    .rate-table { width: 100%; border-collapse: collapse; margin-top: 30px; }
    .rate-table td { padding: 10px; border: 1px solid #000; }
</style>

<div class="header">
    <div>
        <h1 style="margin: 0;">CARRIER RATE CONFIRMATION</h1>
        <div style="font-size: 14px;">TMS Reference: {{load_number}}</div>
    </div>
    <div style="text-align: right;">
        <strong>{{company_name}}</strong><br>
        Dispatcher: (555) 000-0000
    </div>
</div>

<div class="main-grid">
    <div class="stop">
        <div class="stop-header">PICKUP</div>
        <strong>{{shipper_name}}</strong><br>
        {{shipper_address}}<br>
        Date: {{pickup_date}}
    </div>
    <div class="stop">
        <div class="stop-header">DELIVERY</div>
        <strong>{{consignee_name}}</strong><br>
        {{consignee_address}}<br>
        Date: {{delivery_date}}
    </div>
</div>

<div style="margin-top: 20px;">
    <strong>EQUIPMENT REQUIRED:</strong> 53' Dry Van | <strong>WEIGHT:</strong> {{total_weight}} LBS
</div>

<table class="rate-table">
    <tr>
        <td style="font-weight: bold;">AGREED CARRIER RATE</td>
        <td style="text-align: right; font-weight: bold; font-size: 18px;">$0.00</td>
    </tr>
</table>

<div style="margin-top: 30px; border: 1px solid #000; padding: 15px; font-size: 11px;">
    <strong>CARRIER INSTRUCTIONS:</strong><br>
    - Driver must call upon arrival and departure of all stops.<br>
    - All paperwork must be submitted via the TMS portal within 24 hours of delivery.<br>
    - No double brokering allowed.
</div>
`
    }
};

export default async function TemplateEditorPage({ params }: { params: Promise<{ slug: string }> }) {
    const { slug } = await params;
    const supabase = await createClient();

    // Get organization ID
    const { data: orgs } = await supabase.from('organizations').select('id').limit(1).single();
    const orgId = orgs?.id;

    if (!orgId) {
        return <div className="p-8 text-center text-slate-500">Organization not found.</div>;
    }

    // Get existing template
    const { data: template } = await supabase
        .from('document_templates')
        .select('*')
        .eq('org_id', orgId)
        .eq('slug', slug)
        .single();

    const defaultData = DEFAULT_TEMPLATES[slug] || { 
        name: slug.replace(/-/g, ' ').toUpperCase(), 
        type: 'General', 
        content: '<!-- New Template -->' 
    };

    return (
        <div className="h-[calc(100vh-100px)]">
            <TemplateEditor
                initialContent={template?.content || defaultData.content}
                templateName={template?.name || defaultData.name}
                slug={slug}
                orgId={orgId}
                type={template?.type || defaultData.type}
            />
        </div>
    );
}
