-- Create calendar_events table
create table public.calendar_events (
    id uuid default gen_random_uuid() primary key,
    event_number bigint generated by default as identity (start with 1000),
    event_date date not null,
    event_time time without time zone,
    event_type text not null check (event_type in ('Appointment', 'Task', 'Event')),
    description text not null,
    notes text,
    user_id uuid references auth.users(id) on delete cascade not null,
    status text default 'Pending' check (status in ('Pending', 'In Progress', 'Completed', 'Cancelled')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    created_by uuid references auth.users(id),
    last_modified_date timestamp with time zone default timezone('utc'::text, now()) not null,
    last_modified_by uuid references auth.users(id)
);

alter table public.calendar_events enable row level security;

-- RLS Policies
create policy "Users can manage their own calendar events" on public.calendar_events
  for all using (user_id = auth.uid());
